version: '3'

services:

  # Data bases
  mongo-db:
    image: mongo:4.4
    restart: always
    command: --nojournal
    hostname: mongo-db
    container_name: fiware-mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  # Orion is the context broker
  orion:
    image: fiware/orion:latest
    restart: always
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -corsOrigin __ALL -corsMaxAge 600

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    hostname: mosquitto
    container_name: fiware-mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # MQTT Broker to NGSI
  iot-agent:
    image: fiware/iotagent-ul:latest
    restart: always
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
      - mosquitto
    expose:
      - "4041"
    ports:
      - "4041:4041"
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentul
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883


  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wirecloud-static:/var/www/static:ro
    depends_on:
      - wirecloud

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=wirepass   # Change this password!
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  elasticsearch:
    restart: always
    image: elasticsearch:2.4
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    command: elasticsearch -Des.index.max_result_window=50000

  memcached:
    restart: always
    image: memcached:1
    command: memcached -m 2048m

  wirecloud:
    restart: always
    image: fiware/wirecloud
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - memcached
      - ngsiproxy
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - NGSI_PROXY_URL=http://ngsiproxy:1026
      # - DEFAULT_THEME=wirecloud.defaulttheme
      - DB_HOST=postgres
      - DB_PASSWORD=wirepass   # Change this password!
      - FORWARDED_ALLOW_IPS=*
      - ELASTICSEARCH2_URL=http://elasticsearch:9200/
      - MEMCACHED_LOCATION=memcached:11211
      # Uncomment the following environment variables to enable IDM integration
      #- FIWARE_IDM_SERVER=${FIWARE_IDM_SERVER}
      #- SOCIAL_AUTH_FIWARE_KEY=${SOCIAL_AUTH_FIWARE_KEY}
      #- SOCIAL_AUTH_FIWARE_SECRET=${SOCIAL_AUTH_FIWARE_SECRET}
    volumes:
      - ./wirecloud-data:/opt/wirecloud_instance/data
      - ./wirecloud-static:/var/www/static
   ngsiproxy:
    image: fiware/ngsiproxy
    ports:
     - "3100:3100"
    environment:
     - DEBUG=True
     - SERVER_PORT=1026

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data

volumes:
  db-data:
